// Generated by gencpp from file robot_update/updateFWSignalResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALRESPONSE_H
#define ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_update
{
template <class ContainerAllocator>
struct updateFWSignalResponse_
{
  typedef updateFWSignalResponse_<ContainerAllocator> Type;

  updateFWSignalResponse_()
    : signalSuccess(false)  {
    }
  updateFWSignalResponse_(const ContainerAllocator& _alloc)
    : signalSuccess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _signalSuccess_type;
  _signalSuccess_type signalSuccess;





  typedef boost::shared_ptr< ::robot_update::updateFWSignalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_update::updateFWSignalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct updateFWSignalResponse_

typedef ::robot_update::updateFWSignalResponse_<std::allocator<void> > updateFWSignalResponse;

typedef boost::shared_ptr< ::robot_update::updateFWSignalResponse > updateFWSignalResponsePtr;
typedef boost::shared_ptr< ::robot_update::updateFWSignalResponse const> updateFWSignalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_update::updateFWSignalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_update::updateFWSignalResponse_<ContainerAllocator1> & lhs, const ::robot_update::updateFWSignalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.signalSuccess == rhs.signalSuccess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_update::updateFWSignalResponse_<ContainerAllocator1> & lhs, const ::robot_update::updateFWSignalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_update

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_update::updateFWSignalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_update::updateFWSignalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_update::updateFWSignalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29b721cc9130c4edef310b7dcc8f7731";
  }

  static const char* value(const ::robot_update::updateFWSignalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29b721cc9130c4edULL;
  static const uint64_t static_value2 = 0xef310b7dcc8f7731ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_update/updateFWSignalResponse";
  }

  static const char* value(const ::robot_update::updateFWSignalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: Signal \n"
"bool signalSuccess\n"
;
  }

  static const char* value(const ::robot_update::updateFWSignalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signalSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct updateFWSignalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_update::updateFWSignalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_update::updateFWSignalResponse_<ContainerAllocator>& v)
  {
    s << indent << "signalSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signalSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALRESPONSE_H
