// Generated by gencpp from file robot_update/updateFWSignal.msg
// DO NOT EDIT!


#ifndef ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNAL_H
#define ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNAL_H

#include <ros/service_traits.h>


#include <robot_update/updateFWSignalRequest.h>
#include <robot_update/updateFWSignalResponse.h>


namespace robot_update
{

struct updateFWSignal
{

typedef updateFWSignalRequest Request;
typedef updateFWSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct updateFWSignal
} // namespace robot_update


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_update::updateFWSignal > {
  static const char* value()
  {
    return "9c5eee2d22e1212d864abfe1f867776b";
  }

  static const char* value(const ::robot_update::updateFWSignal&) { return value(); }
};

template<>
struct DataType< ::robot_update::updateFWSignal > {
  static const char* value()
  {
    return "robot_update/updateFWSignal";
  }

  static const char* value(const ::robot_update::updateFWSignal&) { return value(); }
};


// service_traits::MD5Sum< ::robot_update::updateFWSignalRequest> should match
// service_traits::MD5Sum< ::robot_update::updateFWSignal >
template<>
struct MD5Sum< ::robot_update::updateFWSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_update::updateFWSignal >::value();
  }
  static const char* value(const ::robot_update::updateFWSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_update::updateFWSignalRequest> should match
// service_traits::DataType< ::robot_update::updateFWSignal >
template<>
struct DataType< ::robot_update::updateFWSignalRequest>
{
  static const char* value()
  {
    return DataType< ::robot_update::updateFWSignal >::value();
  }
  static const char* value(const ::robot_update::updateFWSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_update::updateFWSignalResponse> should match
// service_traits::MD5Sum< ::robot_update::updateFWSignal >
template<>
struct MD5Sum< ::robot_update::updateFWSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_update::updateFWSignal >::value();
  }
  static const char* value(const ::robot_update::updateFWSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_update::updateFWSignalResponse> should match
// service_traits::DataType< ::robot_update::updateFWSignal >
template<>
struct DataType< ::robot_update::updateFWSignalResponse>
{
  static const char* value()
  {
    return DataType< ::robot_update::updateFWSignal >::value();
  }
  static const char* value(const ::robot_update::updateFWSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNAL_H
