// Generated by gencpp from file robot_update/updateFWSignalRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALREQUEST_H
#define ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_update
{
template <class ContainerAllocator>
struct updateFWSignalRequest_
{
  typedef updateFWSignalRequest_<ContainerAllocator> Type;

  updateFWSignalRequest_()
    : FW_name()  {
    }
  updateFWSignalRequest_(const ContainerAllocator& _alloc)
    : FW_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _FW_name_type;
  _FW_name_type FW_name;





  typedef boost::shared_ptr< ::robot_update::updateFWSignalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_update::updateFWSignalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct updateFWSignalRequest_

typedef ::robot_update::updateFWSignalRequest_<std::allocator<void> > updateFWSignalRequest;

typedef boost::shared_ptr< ::robot_update::updateFWSignalRequest > updateFWSignalRequestPtr;
typedef boost::shared_ptr< ::robot_update::updateFWSignalRequest const> updateFWSignalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_update::updateFWSignalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_update::updateFWSignalRequest_<ContainerAllocator1> & lhs, const ::robot_update::updateFWSignalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.FW_name == rhs.FW_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_update::updateFWSignalRequest_<ContainerAllocator1> & lhs, const ::robot_update::updateFWSignalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_update

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_update::updateFWSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_update::updateFWSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_update::updateFWSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3fb21c13fb0cf19067695d456c52e20";
  }

  static const char* value(const ::robot_update::updateFWSignalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3fb21c13fb0cf19ULL;
  static const uint64_t static_value2 = 0x067695d456c52e20ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_update/updateFWSignalRequest";
  }

  static const char* value(const ::robot_update::updateFWSignalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: FW name\n"
"string FW_name\n"
"\n"
;
  }

  static const char* value(const ::robot_update::updateFWSignalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FW_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct updateFWSignalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_update::updateFWSignalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_update::updateFWSignalRequest_<ContainerAllocator>& v)
  {
    s << indent << "FW_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.FW_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_UPDATE_MESSAGE_UPDATEFWSIGNALREQUEST_H
