// Generated by gencpp from file robot_navigation/GARequestRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_GAREQUESTREQUEST_H
#define ROBOT_NAVIGATION_MESSAGE_GAREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_navigation
{
template <class ContainerAllocator>
struct GARequestRequest_
{
  typedef GARequestRequest_<ContainerAllocator> Type;

  GARequestRequest_()
    : start()
    , destinations()  {
    }
  GARequestRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , destinations(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _start_type;
  _start_type start;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _destinations_type;
  _destinations_type destinations;





  typedef boost::shared_ptr< ::robot_navigation::GARequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::GARequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GARequestRequest_

typedef ::robot_navigation::GARequestRequest_<std::allocator<void> > GARequestRequest;

typedef boost::shared_ptr< ::robot_navigation::GARequestRequest > GARequestRequestPtr;
typedef boost::shared_ptr< ::robot_navigation::GARequestRequest const> GARequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::GARequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::GARequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_navigation::GARequestRequest_<ContainerAllocator1> & lhs, const ::robot_navigation::GARequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.destinations == rhs.destinations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_navigation::GARequestRequest_<ContainerAllocator1> & lhs, const ::robot_navigation::GARequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::GARequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::GARequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::GARequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a12a89f1d77ce56f8af171362a3a2bd7";
  }

  static const char* value(const ::robot_navigation::GARequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa12a89f1d77ce56fULL;
  static const uint64_t static_value2 = 0x8af171362a3a2bd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/GARequestRequest";
  }

  static const char* value(const ::robot_navigation::GARequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request: An array of strings\n"
"string start\n"
"string[] destinations\n"
"\n"
;
  }

  static const char* value(const ::robot_navigation::GARequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.destinations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GARequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::GARequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_navigation::GARequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.start);
    s << indent << "destinations[]" << std::endl;
    for (size_t i = 0; i < v.destinations.size(); ++i)
    {
      s << indent << "  destinations[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destinations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_GAREQUESTREQUEST_H
