// Generated by gencpp from file robot_navigation/GARequest.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_GAREQUEST_H
#define ROBOT_NAVIGATION_MESSAGE_GAREQUEST_H

#include <ros/service_traits.h>


#include <robot_navigation/GARequestRequest.h>
#include <robot_navigation/GARequestResponse.h>


namespace robot_navigation
{

struct GARequest
{

typedef GARequestRequest Request;
typedef GARequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GARequest
} // namespace robot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_navigation::GARequest > {
  static const char* value()
  {
    return "51c6edeb2019aac92d28d0824470756f";
  }

  static const char* value(const ::robot_navigation::GARequest&) { return value(); }
};

template<>
struct DataType< ::robot_navigation::GARequest > {
  static const char* value()
  {
    return "robot_navigation/GARequest";
  }

  static const char* value(const ::robot_navigation::GARequest&) { return value(); }
};


// service_traits::MD5Sum< ::robot_navigation::GARequestRequest> should match
// service_traits::MD5Sum< ::robot_navigation::GARequest >
template<>
struct MD5Sum< ::robot_navigation::GARequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::GARequest >::value();
  }
  static const char* value(const ::robot_navigation::GARequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::GARequestRequest> should match
// service_traits::DataType< ::robot_navigation::GARequest >
template<>
struct DataType< ::robot_navigation::GARequestRequest>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::GARequest >::value();
  }
  static const char* value(const ::robot_navigation::GARequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_navigation::GARequestResponse> should match
// service_traits::MD5Sum< ::robot_navigation::GARequest >
template<>
struct MD5Sum< ::robot_navigation::GARequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::GARequest >::value();
  }
  static const char* value(const ::robot_navigation::GARequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::GARequestResponse> should match
// service_traits::DataType< ::robot_navigation::GARequest >
template<>
struct DataType< ::robot_navigation::GARequestResponse>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::GARequest >::value();
  }
  static const char* value(const ::robot_navigation::GARequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_GAREQUEST_H
