// Generated by gencpp from file robot_navigation/GARequestResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_GAREQUESTRESPONSE_H
#define ROBOT_NAVIGATION_MESSAGE_GAREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_navigation
{
template <class ContainerAllocator>
struct GARequestResponse_
{
  typedef GARequestResponse_<ContainerAllocator> Type;

  GARequestResponse_()
    : GA_result()
    , Products()
    , Products_indices()  {
    }
  GARequestResponse_(const ContainerAllocator& _alloc)
    : GA_result(_alloc)
    , Products(_alloc)
    , Products_indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _GA_result_type;
  _GA_result_type GA_result;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _Products_type;
  _Products_type Products;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _Products_indices_type;
  _Products_indices_type Products_indices;





  typedef boost::shared_ptr< ::robot_navigation::GARequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::GARequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GARequestResponse_

typedef ::robot_navigation::GARequestResponse_<std::allocator<void> > GARequestResponse;

typedef boost::shared_ptr< ::robot_navigation::GARequestResponse > GARequestResponsePtr;
typedef boost::shared_ptr< ::robot_navigation::GARequestResponse const> GARequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::GARequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::GARequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_navigation::GARequestResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::GARequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.GA_result == rhs.GA_result &&
    lhs.Products == rhs.Products &&
    lhs.Products_indices == rhs.Products_indices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_navigation::GARequestResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::GARequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::GARequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::GARequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::GARequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee303d60ffabb936581bf507956c6387";
  }

  static const char* value(const ::robot_navigation::GARequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee303d60ffabb936ULL;
  static const uint64_t static_value2 = 0x581bf507956c6387ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/GARequestResponse";
  }

  static const char* value(const ::robot_navigation::GARequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response: An array of strings\n"
"string[] GA_result\n"
"string[] Products\n"
"int32[] Products_indices\n"
;
  }

  static const char* value(const ::robot_navigation::GARequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GA_result);
      stream.next(m.Products);
      stream.next(m.Products_indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GARequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::GARequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_navigation::GARequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "GA_result[]" << std::endl;
    for (size_t i = 0; i < v.GA_result.size(); ++i)
    {
      s << indent << "  GA_result[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.GA_result[i]);
    }
    s << indent << "Products[]" << std::endl;
    for (size_t i = 0; i < v.Products.size(); ++i)
    {
      s << indent << "  Products[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Products[i]);
    }
    s << indent << "Products_indices[]" << std::endl;
    for (size_t i = 0; i < v.Products_indices.size(); ++i)
    {
      s << indent << "  Products_indices[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Products_indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_GAREQUESTRESPONSE_H
