// Generated by gencpp from file robot_navigation/ReplanPath.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_REPLANPATH_H
#define ROBOT_NAVIGATION_MESSAGE_REPLANPATH_H

#include <ros/service_traits.h>


#include <robot_navigation/ReplanPathRequest.h>
#include <robot_navigation/ReplanPathResponse.h>


namespace robot_navigation
{

struct ReplanPath
{

typedef ReplanPathRequest Request;
typedef ReplanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReplanPath
} // namespace robot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_navigation::ReplanPath > {
  static const char* value()
  {
    return "570ec26491df9ed08af93654de135263";
  }

  static const char* value(const ::robot_navigation::ReplanPath&) { return value(); }
};

template<>
struct DataType< ::robot_navigation::ReplanPath > {
  static const char* value()
  {
    return "robot_navigation/ReplanPath";
  }

  static const char* value(const ::robot_navigation::ReplanPath&) { return value(); }
};


// service_traits::MD5Sum< ::robot_navigation::ReplanPathRequest> should match
// service_traits::MD5Sum< ::robot_navigation::ReplanPath >
template<>
struct MD5Sum< ::robot_navigation::ReplanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::ReplanPath >::value();
  }
  static const char* value(const ::robot_navigation::ReplanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::ReplanPathRequest> should match
// service_traits::DataType< ::robot_navigation::ReplanPath >
template<>
struct DataType< ::robot_navigation::ReplanPathRequest>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::ReplanPath >::value();
  }
  static const char* value(const ::robot_navigation::ReplanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_navigation::ReplanPathResponse> should match
// service_traits::MD5Sum< ::robot_navigation::ReplanPath >
template<>
struct MD5Sum< ::robot_navigation::ReplanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::ReplanPath >::value();
  }
  static const char* value(const ::robot_navigation::ReplanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::ReplanPathResponse> should match
// service_traits::DataType< ::robot_navigation::ReplanPath >
template<>
struct DataType< ::robot_navigation::ReplanPathResponse>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::ReplanPath >::value();
  }
  static const char* value(const ::robot_navigation::ReplanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_REPLANPATH_H
