// Generated by gencpp from file robot_navigation/ReplanPathResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_REPLANPATHRESPONSE_H
#define ROBOT_NAVIGATION_MESSAGE_REPLANPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>
#include <std_msgs/Float32.h>

namespace robot_navigation
{
template <class ContainerAllocator>
struct ReplanPathResponse_
{
  typedef ReplanPathResponse_<ContainerAllocator> Type;

  ReplanPathResponse_()
    : planned_path()
    , cost()  {
    }
  ReplanPathResponse_(const ContainerAllocator& _alloc)
    : planned_path(_alloc)
    , cost(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _planned_path_type;
  _planned_path_type planned_path;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _cost_type;
  _cost_type cost;





  typedef boost::shared_ptr< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReplanPathResponse_

typedef ::robot_navigation::ReplanPathResponse_<std::allocator<void> > ReplanPathResponse;

typedef boost::shared_ptr< ::robot_navigation::ReplanPathResponse > ReplanPathResponsePtr;
typedef boost::shared_ptr< ::robot_navigation::ReplanPathResponse const> ReplanPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::ReplanPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_navigation::ReplanPathResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::ReplanPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.planned_path == rhs.planned_path &&
    lhs.cost == rhs.cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_navigation::ReplanPathResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::ReplanPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10fd4e7ff4ebbea1e9b38d66a6c58f35";
  }

  static const char* value(const ::robot_navigation::ReplanPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10fd4e7ff4ebbea1ULL;
  static const uint64_t static_value2 = 0xe9b38d66a6c58f35ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/ReplanPathResponse";
  }

  static const char* value(const ::robot_navigation::ReplanPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path planned_path\n"
"std_msgs/Float32 cost\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::robot_navigation::ReplanPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.planned_path);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReplanPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::ReplanPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_navigation::ReplanPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "planned_path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.planned_path);
    s << indent << "cost: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_REPLANPATHRESPONSE_H
